version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always  
    networks:
      - frontend
    volumes:
      - backend-data:/var/lib/virtual-office

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend  

networks:
  frontend:

volumes:
  backend-data: