version: '3.7'

services:
  backend:
    image: piotrkow1/virtual-office_backend
    ports:
      - "8080:8080"
    restart: always  
    networks:
      - frontend
    volumes:
      - backend-data:/var/lib/virtual-office

  frontend:
    image: piotrkow1/virtual-office_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend  

networks:
  frontend:

volumes:
  backend-data: